### ISSUE TITLE
Using grab values and random in outputs of conditional results

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-extensions#10]
I know we made this work for SC but Im wondering how we could also use those grab values to paste directly in code with other extensions. Maybe it's already there and you can just talk me through it, maybe we can make some adjustments.

**Comment by narcode** [comment]
explained it online already and fixed a little issue. if this is already clear to you maybe close the issue? we can also paste the osc_listener xample in the readme
