### ISSUE TITLE
Possible to navigate the editor with shortkeys?

### ISSUE THREAD

**Issue by tmhglnd** [narcode/codeklavier-extensions#2]
From what I understood the codeklavier doesn't go back in code. Mercury evaluates the entire editor top-to-bottom instead on a per-line basis. This means that `ring`'s added later on could not be used as parameters in a synth if the line of code is not before the initialization of the synth. Would it be possible to easily navigate the editor from the codeklavier. Shortkeys that are available in Mercury:

```
ALT + ARROW_UP    => jump to first line
ALT + ARROW_DOWN  => jump to last line
ALT + ARROW_LEFT  => jump to end of line
ALT + ARROW_RIGHT => jump to beginning

ALT + X => delete entire line the cursor is on
ALT + C => copy entire line the cursor is on
ALT + V => insert-paste entire line the cursor is on
ALT + P => paste-replace entire line the cursor is on
```

**Comment by narcode** [comment]
Hi! Yes it’s possible. I will add these shortcuts in the .ini file…

**Comment by narcode** [comment]
@wooloogooloo please test this ini file and shortcuts with the latest ck_dev branch and let me know
