### ISSUE TITLE
input for ini file improvemen

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-extensions#5]
HI Felipe, 

Currently the ini file minmax only works when both values are floats (so using a non float really messes things up) = this is not such a  big deal. But what is unhandy is that if the min or max value needs to be to 3 decimal places, it also really messes up the scaling. So  ideally there shouldnt be a limitation on the float for minmax - only the float output shoudl be limited to 2 decimal places.

**Comment by narcode** [comment]
Ok no problem. We have to debug this next Wednesday

**Comment by narcode** [comment]
fixed in https://github.com/narcode/codeklavier/commit/d33216b6e561b026128a7599804cba267351e99c
