### ISSUE TITLE
Add exponential scaling option for trills

### ISSUE THREAD

**Issue by tmhglnd** [narcode/codeklavier-extensions#6]
Could you add the possibility for exponential scaling for the trill-maps. Maybe in the form of an optional third argument. Also negative values for scaling output and reverse scaling might be helpful.

**Comment by narcode** [comment]
Yea good idea. Will do. Next week will be ready.

**Comment by narcode** [comment]
done in https://github.com/narcode/codeklavier/commit/e71667404e3b967f3ac7c35394f411503611b0c3

**Comment by tmhglnd** [comment]
Cool, thanks! But would it also be possible to specify the exponent as argument instead of always be a raised to the power of 2?

eg.
```
,minmax(10-1000, 3)
```

**Comment by narcode** [comment]
Ok, it was a Maths diff in the approach. Now i blatantly copied your cool scaling function you did in JS so thanks for that! 💯  
This should work since the last commit https://github.com/narcode/codeklavier/commit/5df677935b6aac857ae0c83bac6c1936c24ae419
