### ISSUE TITLE
error when testing the Mercury extension

### ISSUE THREAD

**Issue by ccrraaiigg** [narcode/codeklavier-extensions#7]
Help?

***

craig@rhythm codeklavier-ck_dev 30> python3 ./codeklavier.py -p hybrid -i ~/forks/codeklavier-extensions/mercury.ini
Traceback (most recent call last):
  File "./codeklavier.py", line 16, in <module>
    from CK_Setup import Setup, BColors
ModuleNotFoundError: No module named 'CK_Setup'
craig@rhythm codeklavier-ck_dev 31>

**Comment by narcode** [comment]
Hi!

I think this is because we need to export a PATH to the CK_modules in your bash/shell profile.

something on the lines of:
````
# Modules for the CodeKlavier
 PYTHONPATH="/path/to/the/CodeKlavier:$PYTHONPATH"
 export PYTHONPATH
````
you can also refer to the **Modules** part of the Codeklavier [README](https://github.com/narcode/codeklavier/blob/master/README.md)

**Comment by ccrraaiigg** [comment]
Thanks!
