### ISSUE TITLE
option to not auto evaluate or enter when using toggle

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/codeklavier-extensions#8]
At the moment the toggle includes an auto evalute and next line (or to bottom of the page - im not actually sure). THis makes it impossible to use the direct "hello world" input in combination with "motippets".

Also, it seems to me that the current "hello world" input only allows single letter characters to be pasted and NOT  words. I guess this is not a huge disaster but it didnt use to be the case...

**Comment by narcode** [comment]
fixed in https://github.com/narcode/codeklavier/commit/fc2ab66c669efa468ab5ef49bb1cd4415bee597e

make another issue for the chars vs words
